markdown: kramdown
pygments: true
permalink: /:year/:month/:day/:title
auto: true

name: formhub blog
url: http://blog.formhub.org
description: updates from the formhub team on your favorite data gathering platform.
twitter: formhub
github: modilabs
gravatar_url: 

 
